name: Build & Push to DockerHub

on:
  push:
    branches:
      - master
      - testnet

jobs:
  build:
    name: Build & Push to DockerHub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }} | docker login -u ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME}} --password-stdin

      - name: Build and push Rollup Services image to DockerHub
        run: |
          git clone https://github.com/ethereum-optimism/docker.git \
              $HOME/docker
          cd $HOME/docker
          BRANCH=${GITHUB_REF##*/}
          REMOTE="https://github.com/${{ github.repository }}"
          ./build.sh -s data-transport-layer -b $BRANCH -r $REMOTE
          if [ $BRANCH == 'master' ]; then
              docker push ethereumoptimism/data-transport-layer:latest
          elif [[ $BRANCH == 'testnet' ]]; then
              docker push ethereumoptimism/data-transport-layer:$BRANCH
          fi
      - name: Logout of DockerHub
        run: docker logout
